const PRAYERS=[
{id:'Fajr',pt:'Fajr',ar:'الفجر',rakah:2,loud:[1,2],desc:'2 rak‘ahs Fard'},
{id:'Dhuhr',pt:'Dhuhr',ar:'الظهر',rakah:4,loud:[],desc:'4 rak‘ahs Fard'},
{id:'Asr',pt:'Asr',ar:'العصر',rakah:4,loud:[],desc:'4 rak‘ahs Fard'},
{id:'Maghrib',pt:'Maghrib',ar:'المغرب',rakah:3,loud:[1,2],desc:'3 rak‘ahs Fard'},
{id:'Isha',pt:'Isha',ar:'العشاء',rakah:4,loud:[1,2],desc:'4 rak‘ahs Fard'}
];
const KAABA={lat:21.422487,lng:39.826206};
const STORAGE={settings:'salah-settings-v2',history:'salah-history-v2',timings:'salah-timings-v2'};
const defaultSettings={city:'',country:'Brazil',method:'3',school:'0',lat:null,lng:null,mode:'city'};
let settings=loadJSON(STORAGE.settings,defaultSettings),dayData=null,timer=null,guideState=null;

const REC={
TAKBIR:{name:'Takbir',ar:'اللَّهُ أَكْبَرُ',tr:'Allahu Akbar',pt:'Allah é o Maior.'},
OPENING:{name:'Du‘a de abertura — Sunnah',ar:'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، وَتَبَارَكَ اسْمُكَ، وَتَعَالَى جَدُّكَ، وَلَا إِلَهَ غَيْرُكَ',tr:'Subhanaka Allahumma wa bihamdika, wa tabarakasmuka, wa ta‘ala jadduka, wa la ilaha ghayruk.',pt:'Glória e louvor a Ti, ó Allah. Bendito é o Teu nome, exaltada é a Tua majestade, e não há divindade além de Ti.'},
TAWWUDH:{name:'Ta‘awwudh',ar:'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',tr:'A‘udhu billahi min ash-shaytan ir-rajim.',pt:'Busco refúgio em Allah contra Satanás, o amaldiçoado.'},
BASMALA:{name:'Basmala',ar:'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',tr:'Bismillahir-Rahmanir-Rahim.',pt:'Em nome de Allah, o Misericordioso, o Compassivo.'},
FATIHA:{name:'Surah Al-Fatihah — completa',ar:'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ\nالرَّحْمَٰنِ الرَّحِيمِ\nمَالِكِ يَوْمِ الدِّينِ\nإِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ\nاهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ\nصِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',tr:'Al-hamdu lillahi Rabbil-‘alamin. Ar-Rahmanir-Rahim. Maliki yawmid-din. Iyyaka na‘budu wa iyyaka nasta‘in. Ihdinas-siratal-mustaqim. Siratal-ladhina an‘amta ‘alayhim ghayril-maghdubi ‘alayhim wa lad-dallin.',pt:'Todo louvor pertence a Allah, Senhor dos mundos; o Misericordioso, o Compassivo; Soberano do Dia do Juízo. Só a Ti adoramos e só de Ti buscamos ajuda. Guia-nos pelo caminho reto, o caminho daqueles a quem agraciaste, não o dos que incorreram em ira nem o dos desviados.'},
AMEEN:{name:'Após Al-Fatihah',ar:'آمِينَ',tr:'Amin.',pt:'Ó Allah, aceita / assim seja.'},
IKHLAS:{name:'Surah adicional — exemplo: Al-Ikhlas',ar:'قُلْ هُوَ اللَّهُ أَحَدٌ\nاللَّهُ الصَّمَدُ\nلَمْ يَلِدْ وَلَمْ يُولَدْ\nوَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ',tr:'Qul huwa Allahu ahad. Allahus-samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad.',pt:'Dize: Ele é Allah, Único. Allah, o Absoluto. Não gerou nem foi gerado. E nada é comparável a Ele.'},
RUKU:{name:'Dhikr do Ruku‘',ar:'سُبْحَانَ رَبِّيَ الْعَظِيمِ',tr:'Subhana Rabbiyal-‘Azim.',pt:'Glorificado seja meu Senhor, o Magnífico.'},
RISE:{name:'Ao levantar do Ruku‘',ar:'سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ',tr:'Sami‘Allahu liman hamidah.',pt:'Allah ouve aquele que O louva.'},
HAMD:{name:'Já em pé',ar:'رَبَّنَا وَلَكَ الْحَمْدُ',tr:'Rabbana wa lakal-hamd.',pt:'Nosso Senhor, e a Ti pertence todo louvor.'},
SUJUD:{name:'Dhikr do Sujud',ar:'سُبْحَانَ رَبِّيَ الْأَعْلَى',tr:'Subhana Rabbiyal-A‘la.',pt:'Glorificado seja meu Senhor, o Altíssimo.'},
FORGIVE:{name:'Entre as duas prostrações',ar:'رَبِّ اغْفِرْ لِي',tr:'Rabbighfir li.',pt:'Meu Senhor, perdoa-me.'},
TASHAHHUD:{name:'Tashahhud — completo',ar:'التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ',tr:'At-tahiyyatu lillahi was-salawatu wat-tayyibat. As-salamu ‘alayka ayyuhan-nabiyyu wa rahmatullahi wa barakatuh. As-salamu ‘alayna wa ‘ala ‘ibadillahis-salihin. Ashhadu an la ilaha illallah, wa ashhadu anna Muhammadan ‘abduhu wa rasuluh.',pt:'Todas as saudações, orações e boas palavras pertencem a Allah. A paz esteja sobre ti, ó Profeta, e a misericórdia de Allah e Suas bênçãos. A paz esteja sobre nós e sobre os servos virtuosos de Allah. Testemunho que não há divindade além de Allah e testemunho que Muhammad é Seu servo e Mensageiro.'},
SALAWAT:{name:'Salat Ibrahimiyyah',ar:'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ. اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ',tr:'Allahumma salli ‘ala Muhammadin wa ‘ala ali Muhammad, kama sallayta ‘ala Ibrahima wa ‘ala ali Ibrahim, innaka Hamidun Majid. Allahumma barik ‘ala Muhammadin wa ‘ala ali Muhammad, kama barakta ‘ala Ibrahima wa ‘ala ali Ibrahim, innaka Hamidun Majid.',pt:'Ó Allah, concede bênçãos a Muhammad e à família de Muhammad, assim como concedeste bênçãos a Ibrahim e à família de Ibrahim. Tu és Louvável, Glorioso. Ó Allah, abençoa Muhammad e a família de Muhammad, assim como abençoaste Ibrahim e a família de Ibrahim. Tu és Louvável, Glorioso.'},
DUA_END:{name:'Du‘a antes do Taslim — Sunnah recomendada',ar:'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ جَهَنَّمَ، وَمِنْ عَذَابِ الْقَبْرِ، وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ، وَمِنْ شَرِّ فِتْنَةِ الْمَسِيحِ الدَّجَّالِ',tr:'Allahumma inni a‘udhu bika min ‘adhabi Jahannam, wa min ‘adhabil-qabr, wa min fitnatil-mahya wal-mamat, wa min sharri fitnatil-Masihid-Dajjal.',pt:'Ó Allah, busco refúgio em Ti do castigo do Inferno, do castigo da sepultura, das provações da vida e da morte e do mal da provação do falso Messias.'},
SALAM:{name:'Taslim',ar:'السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ',tr:'Assalamu ‘alaykum wa rahmatullah.',pt:'Que a paz e a misericórdia de Allah estejam sobre vocês.'}
};

function loadJSON(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return v??structuredClone(fallback)}catch{return structuredClone(fallback)}}
function saveJSON(key,val){localStorage.setItem(key,JSON.stringify(val))}
function todayKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function history(){return loadJSON(STORAGE.history,{})}
function currentDone(){return history()[todayKey()]||{}}
function setDone(id,done){const h=history(),k=todayKey();h[k]=h[k]||{};h[k][id]=done;if(!Object.values(h[k]).some(Boolean))delete h[k];saveJSON(STORAGE.history,h);renderPrayerCards();renderHistory()}
function cleanTime(v){return(v||'—').replace(/\s*\(.+?\)\s*/g,'').trim()}
function timeToDate(hm,base=new Date()){if(!hm||hm==='—')return null;const [h,m]=hm.split(':').map(Number);const d=new Date(base);d.setHours(h,m,0,0);return d}
function formatDate(d){return new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'numeric',month:'long'}).format(d)}
function setStatus(msg,type='success'){const el=document.getElementById('settingsStatus');el.className=`notice ${type}`;el.textContent=msg}

async function fetchTimings(){
 if(!settings.city&&settings.mode!=='coords'){showTab('settings');setStatus('Informe sua cidade ou use a localização do dispositivo.','error');return}
 try{
  setStatus('Calculando horários…','success');
  const now=new Date(),apiDate=`${String(now.getDate()).padStart(2,'0')}-${String(now.getMonth()+1).padStart(2,'0')}-${now.getFullYear()}`;let url;
  if(settings.mode==='coords'&&settings.lat!=null&&settings.lng!=null)url=`https://api.aladhan.com/v1/timings/${apiDate}?latitude=${encodeURIComponent(settings.lat)}&longitude=${encodeURIComponent(settings.lng)}&method=${settings.method}&school=${settings.school}`;
  else url=`https://api.aladhan.com/v1/timingsByCity/${apiDate}?city=${encodeURIComponent(settings.city)}&country=${encodeURIComponent(settings.country)}&method=${settings.method}&school=${settings.school}`;
  const res=await fetch(url);if(!res.ok)throw new Error('Não foi possível consultar os horários.');const json=await res.json();if(json.code!==200||!json.data)throw new Error('Resposta inválida do serviço de horários.');
  dayData=json.data;saveJSON(STORAGE.timings,{key:todayKey(),data:dayData,settings});if(json.data.meta?.latitude!=null){settings.lat=json.data.meta.latitude;settings.lng=json.data.meta.longitude;saveJSON(STORAGE.settings,settings)}renderAll();setStatus('Horários atualizados.','success');
 }catch(e){const cached=loadJSON(STORAGE.timings,null);if(cached?.key===todayKey()){dayData=cached.data;renderAll();setStatus('Usando horários salvos de hoje.','error')}else setStatus(e.message||'Erro ao calcular horários.','error')}
}
function renderAll(){renderHeader();renderPrayerCards();renderExtras();renderHistory();renderQibla();renderLearn();updateCountdown()}
function renderHeader(){const now=new Date();let line=formatDate(now);const h=dayData?.date?.hijri;if(h)line+=` • ${h.day} ${h.month?.en||''} ${h.year} AH`;document.getElementById('dateLine').textContent=line;document.getElementById('locationPill').textContent=settings.mode==='coords'?'Localização atual':(settings.city||'Configurar localização')}
function getCurrentNext(){if(!dayData)return{current:null,next:null};const now=new Date(),list=PRAYERS.map(p=>({...p,date:timeToDate(cleanTime(dayData.timings[p.id]))}));for(let i=0;i<list.length;i++){const end=i<list.length-1?list[i+1].date:new Date(now.getFullYear(),now.getMonth(),now.getDate()+1,0,0,0);if(now>=list[i].date&&now<end)return{current:list[i],next:list[i+1]||null}}if(now<list[0].date)return{current:null,next:list[0]};return{current:list.at(-1),next:null}}
function updateCountdown(){clearTimeout(timer);const name=document.getElementById('nextPrayerName'),ct=document.getElementById('countdown'),btn=document.getElementById('startNextBtn');if(!dayData){name.textContent='Configure sua localização';ct.textContent='Os horários serão calculados para sua cidade.';btn.disabled=true;return}const{current,next}=getCurrentNext();const now=new Date();let target=next;if(!target)target={...PRAYERS[0],date:timeToDate(cleanTime(dayData.timings.Fajr),new Date(now.getFullYear(),now.getMonth(),now.getDate()+1))};const diff=Math.max(0,target.date-now),h=Math.floor(diff/3600000),m=Math.floor(diff%3600000/60000),s=Math.floor(diff%60000/1000);name.textContent=target.pt;ct.textContent=`${target.pt} começa em ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')} • ${target.date.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`;btn.disabled=false;btn.onclick=()=>openGuide(target.id,false);document.querySelectorAll('.prayer-card').forEach(x=>x.classList.toggle('current',x.dataset.id===current?.id));timer=setTimeout(updateCountdown,1000)}
function renderPrayerCards(){const wrap=document.getElementById('prayerCards'),done=currentDone();wrap.innerHTML=PRAYERS.map(p=>`<article class="prayer-card ${done[p.id]?'done':''}" data-id="${p.id}"><div class="prayer-name">${p.pt}</div><div class="arabic">${p.ar}</div><div class="time">${dayData?cleanTime(dayData.timings[p.id]):'—'}</div><div class="rakah">${p.desc}</div><label class="checkrow"><input type="checkbox" data-check="${p.id}" ${done[p.id]?'checked':''}>${done[p.id]?'Realizada':'Marcar realizada'}</label><button class="btn btn-ghost" data-start="${p.id}">Guia completo</button></article>`).join('');wrap.querySelectorAll('[data-check]').forEach(el=>el.onchange=e=>setDone(e.target.dataset.check,e.target.checked));wrap.querySelectorAll('[data-start]').forEach(el=>el.onclick=e=>openGuide(e.currentTarget.dataset.start,false));const n=PRAYERS.filter(p=>done[p.id]).length;document.getElementById('progressText').textContent=`${n} de 5 concluídas`;document.getElementById('progressPct').textContent=`${n*20}%`;document.getElementById('progressBar').style.width=`${n*20}%`;updateCountdown()}
function renderExtras(){const x=document.getElementById('extraTimes');if(!dayData){x.innerHTML='<div class="mini"><span>Nascer do sol</span><strong>—</strong></div>';return}x.innerHTML=[['Nascer do sol','Sunrise'],['Meia-noite','Midnight'],['Imsak','Imsak']].map(([a,b])=>`<div class="mini"><span>${a}</span><strong>${cleanTime(dayData.timings[b])}</strong></div>`).join('')}
function renderHistory(){const h=history(),grid=document.getElementById('historyGrid');if(!grid)return;let html='';for(let i=27;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=todayKey(d),rec=h[k]||{},n=PRAYERS.filter(p=>rec[p.id]).length;html+=`<div class="day ${n===5?'full':n>0?'partial':''}" title="${formatDate(d)}: ${n}/5"><span>${d.getDate()}</span><small>${n}/5</small></div>`}grid.innerHTML=html}
function bearing(lat1,lon1,lat2,lon2){const r=x=>x*Math.PI/180,d=x=>x*180/Math.PI,y=Math.sin(r(lon2-lon1))*Math.cos(r(lat2)),x=Math.cos(r(lat1))*Math.sin(r(lat2))-Math.sin(r(lat1))*Math.cos(r(lat2))*Math.cos(r(lon2-lon1));return(d(Math.atan2(y,x))+360)%360}
function renderQibla(){const a=document.getElementById('qiblaAngle'),t=document.getElementById('qiblaText'),n=document.getElementById('qiblaNeedle');if(settings.lat==null||settings.lng==null){a.textContent='—';t.textContent='Configure sua localização para calcular a direção.';n.style.transform='translate(-50%,-100%) rotate(0deg)';return}const b=bearing(Number(settings.lat),Number(settings.lng),KAABA.lat,KAABA.lng);a.textContent=`${Math.round(b)}°`;t.textContent=`Qiblah aproximadamente a ${Math.round(b)}° do norte geográfico.`;n.style.transform=`translate(-50%,-100%) rotate(${b}deg)`}
function renderLearn(){document.getElementById('learnPrayerCards').innerHTML=PRAYERS.map(p=>`<article class="learn-card"><h4>${p.pt} <span class="arabic">${p.ar}</span></h4><p class="small">${p.desc}. O guia mostra cada recitação integralmente, com transliteração, significado e repetições.</p><button class="btn btn-green" data-practice="${p.id}">Praticar guia completo</button></article>`).join('');document.querySelectorAll('[data-practice]').forEach(b=>b.onclick=()=>openGuide(b.dataset.practice,true))}

function rr(key,repeat='1×',note=''){return{...REC[key],repeat,note}}
function recitationMode(p,r){return p.loud.includes(r)?'Recitação tradicionalmente audível nesta rak‘ah':'Recitação tradicionalmente silenciosa nesta rak‘ah'}
function prayerSequence(id){
 const p=PRAYERS.find(x=>x.id===id),seq=[];
 seq.push({type:'prep',title:`Preparação para ${p.pt}`,instruction:`${p.pt}: ${p.desc}. Faça Wudu quando necessário, cubra a ‘awrah, fique em local limpo e volte-se para a Qiblah. A intenção (niyyah) é no coração; não existe uma frase obrigatória específica para dizê-la.`,badge:'Antes de começar'});
 seq.push({title:'Takbir de abertura',instruction:'Em pé, voltado para a Qiblah, inicie a Salah. Depois coloque as mãos conforme a prática que você segue.',badge:'Início da oração',recs:[rr('TAKBIR'),rr('OPENING','1×','Du‘a de abertura recomendada. Há outras fórmulas autênticas; esta é uma forma comum.'),rr('TAWWUDH')]});
 for(let r=1;r<=p.rakah;r++){
  const firstTwo=r<=2;
  seq.push({title:`Rak‘ah ${r} — Qiyam e recitação`,instruction:`Permaneça em pé. ${recitationMode(p,r)}. ${firstTwo?'Após Al-Fatihah, recite uma surah ou alguns versículos. O guia usa Al-Ikhlas como exemplo completo.':'Nesta rak‘ah, o guia segue a forma comum de recitar Al-Fatihah sem acrescentar uma segunda surah.'}`,badge:`Rak‘ah ${r}/${p.rakah}`,recs:[rr('BASMALA'),rr('FATIHA'),rr('AMEEN'),...(firstTwo?[rr('IKHLAS','1×','Al-Ikhlas é apenas um exemplo. Pode ser substituída por outra surah ou passagem do Alcorão.')]:[])]});
  seq.push({title:`Rak‘ah ${r} — Ruku‘`,instruction:'Diga o Takbir ao inclinar-se. No Ruku‘, mantenha-se inclinado e recite o tasbih.',badge:'Inclinação',recs:[rr('TAKBIR'),rr('RUKU','3×','Repita a frase três vezes no guia.') ]});
  seq.push({title:`Rak‘ah ${r} — levantar do Ruku‘`,instruction:'Retorne completamente à posição em pé antes de seguir para o Sujud.',badge:'I‘tidal',recs:[rr('RISE'),rr('HAMD')]});
  seq.push({title:`Rak‘ah ${r} — primeiro Sujud`,instruction:'Diga o Takbir e faça a primeira prostração. Recite o tasbih durante o Sujud.',badge:'1º Sujud',recs:[rr('TAKBIR'),rr('SUJUD','3×','Repita a frase três vezes no guia.')]});
  seq.push({title:`Rak‘ah ${r} — sentar entre os dois Sujud`,instruction:'Diga o Takbir, sente-se e peça perdão a Allah.',badge:'Jalsah',recs:[rr('TAKBIR'),rr('FORGIVE','2×','O guia usa “Rabbighfir li” duas vezes, uma forma transmitida na Sunnah.')]});
  seq.push({title:`Rak‘ah ${r} — segundo Sujud`,instruction:'Diga o Takbir e faça a segunda prostração, repetindo o mesmo dhikr.',badge:'2º Sujud',recs:[rr('TAKBIR'),rr('SUJUD','3×')]});
  const last=r===p.rakah;
  if(last){
   seq.push({title:'Sentar para o Tashahhud final',instruction:'Após o segundo Sujud, diga o Takbir e permaneça sentado. Recite o Tashahhud completo, depois a Salat Ibrahimiyyah. O du‘a de proteção mostrado em seguida é recomendado antes do Taslim.',badge:'Sentada final',recs:[rr('TAKBIR'),rr('TASHAHHUD'),rr('SALAWAT'),rr('DUA_END','1×','Du‘a recomendado antes do Taslim; outras súplicas autênticas também podem ser feitas.')]});
   seq.push({title:'Taslim — encerrar a Salah',instruction:'Vire a cabeça para a direita e diga a saudação uma vez; depois vire para a esquerda e repita a mesma saudação uma vez.',badge:'Final',recs:[rr('SALAM','2×','1× para a direita + 1× para a esquerda.')]});
  }else if(r===2&&p.rakah>2){
   seq.push({title:'Tashahhud intermediário',instruction:'Após a segunda rak‘ah, diga o Takbir, sente-se e recite o Tashahhud. Depois levante para a próxima rak‘ah dizendo Allahu Akbar.',badge:'Após 2 rak‘ahs',recs:[rr('TAKBIR'),rr('TASHAHHUD'),rr('TAKBIR','1×','Diga ao levantar-se para a próxima rak‘ah.')]});
  }else{
   seq.push({title:`Levantar para a rak‘ah ${r+1}`,instruction:'Após o segundo Sujud, levante-se para a próxima rak‘ah.',badge:'Transição',recs:[rr('TAKBIR')]});
  }
 }
 seq.push({type:'finish',title:`${p.pt} concluída`,instruction:'Alhamdulillah. Você chegou ao final do guia completo.',badge:'Concluída'});return seq;
}
function recHTML(x){return`<div class="recitation"><div class="rec-head"><strong>${x.name}</strong><span class="repeat">${x.repeat||'1×'}</span></div><div class="rec-body"><div class="ar">${x.ar.replaceAll('\n','<br>')}</div><div class="tr">${x.tr}</div><div class="pt">${x.pt}</div>${x.note?`<div class="rec-note">${x.note}</div>`:''}</div></div>`}
function openGuide(id,practice){guideState={id,practice,index:0,seq:prayerSequence(id)};document.getElementById('guideModal').classList.add('open');renderGuide()}
function renderGuide(){const g=guideState,s=g.seq[g.index],p=PRAYERS.find(x=>x.id===g.id);document.getElementById('guideTitle').textContent=`${g.practice?'Treino':'Oração'} • ${p.pt}`;let body='';if(s.type==='prep'){body=`<div class="guide-step"><div class="step-meta"><span class="badge gold">${s.badge}</span><span class="step-count">Etapa ${g.index+1} de ${g.seq.length}</span></div><h4>${s.title}</h4><p class="instruction">${s.instruction}</p><div class="prep"><label><input type="checkbox"> Wudu realizado quando necessário</label><label><input type="checkbox"> Corpo e roupa em condição adequada para Salah</label><label><input type="checkbox"> Voltado para a Qiblah</label><label><input type="checkbox"> Niyyah presente no coração para ${p.pt}</label></div><div class="notice">Este guia apresenta uma forma sunita comum e didática. Detalhes de postura, Basmala, posição das mãos, dedo no Tashahhud, recitação audível e algumas fórmulas variam legitimamente entre escolas jurídicas. O app evita tratar uma dessas variações como a única válida.</div></div>`}else if(s.type==='finish'){body=`<div class="guide-step complete-box"><div class="step-meta"><span class="badge">${s.badge}</span><span class="step-count">Etapa ${g.index+1} de ${g.seq.length}</span></div><div class="complete-icon">✓</div><h4>${s.title}</h4><p class="instruction">${s.instruction}</p>${!g.practice?`<button class="btn btn-green" id="finishPrayer">✓ Marcar ${p.pt} como realizada</button>`:'<div class="notice success">Modo de treino: nenhuma oração foi marcada no histórico.</div>'}</div>`}else{body=`<div class="guide-step"><div class="step-meta"><span class="badge">${s.badge}</span><span class="step-count">Etapa ${g.index+1} de ${g.seq.length}</span></div><h4>${s.title}</h4><p class="instruction">${s.instruction}</p>${(s.recs||[]).map(recHTML).join('')}</div>`}body+=`<div class="guide-nav"><button class="btn btn-ghost" id="prevStep" ${g.index===0?'disabled':''}>← Anterior</button><button class="btn btn-green" id="nextStep" ${g.index===g.seq.length-1?'disabled':''}>Próximo →</button></div>`;document.getElementById('guideContent').innerHTML=body;document.getElementById('prevStep').onclick=()=>{g.index=Math.max(0,g.index-1);renderGuide();document.querySelector('.modal-card').scrollTop=0};document.getElementById('nextStep').onclick=()=>{g.index=Math.min(g.seq.length-1,g.index+1);renderGuide();document.querySelector('.modal-card').scrollTop=0};const finish=document.getElementById('finishPrayer');if(finish)finish.onclick=()=>{setDone(g.id,true);document.getElementById('guideModal').classList.remove('open')}}
function showTab(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.tabbtn').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const t=e.target.closest('[data-tab]');if(t)showTab(t.dataset.tab)});
document.getElementById('closeGuide').onclick=()=>document.getElementById('guideModal').classList.remove('open');document.getElementById('guideModal').onclick=e=>{if(e.target.id==='guideModal')e.currentTarget.classList.remove('open')};document.getElementById('refreshBtn').onclick=fetchTimings;
document.getElementById('saveSettings').onclick=()=>{settings={...settings,city:document.getElementById('city').value.trim(),country:document.getElementById('country').value.trim()||'Brazil',method:document.getElementById('method').value,school:document.getElementById('school').value,mode:'city',lat:null,lng:null};if(!settings.city){setStatus('Informe uma cidade.','error');return}saveJSON(STORAGE.settings,settings);fetchTimings();showTab('today')};
document.getElementById('useLocation').onclick=()=>{if(!navigator.geolocation){setStatus('Seu navegador não oferece geolocalização.','error');return}setStatus('Solicitando permissão de localização…','success');navigator.geolocation.getCurrentPosition(pos=>{settings={...settings,lat:pos.coords.latitude,lng:pos.coords.longitude,mode:'coords'};saveJSON(STORAGE.settings,settings);fetchTimings();showTab('today')},()=>setStatus('Não foi possível acessar sua localização. Informe a cidade manualmente.','error'),{enableHighAccuracy:false,timeout:10000,maximumAge:600000})};
document.getElementById('clearHistory').onclick=()=>{if(confirm('Apagar todo o histórico salvo neste navegador?')){localStorage.removeItem(STORAGE.history);renderPrayerCards();renderHistory()}};
function init(){document.getElementById('city').value=settings.city||'';document.getElementById('country').value=settings.country||'Brazil';document.getElementById('method').value=settings.method||'3';document.getElementById('school').value=settings.school||'0';const cached=loadJSON(STORAGE.timings,null);if(cached?.key===todayKey())dayData=cached.data;renderAll();if(settings.city||settings.mode==='coords')fetchTimings();else showTab('settings')}
init();